version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - swipeswap_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "900", "1", "--appendonly", "yes" ]
volumes:
  swipeswap_pgdata:
